# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linter Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - uses: actions/checkout@v2
    - uses: rbob86/lookml-linter@v3
    - run: |
        python -m linter.main config.example.yaml
        

