# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Linter Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    
 
    - name: Install dependencies 1
      run: |
        python -m pip install --upgrade pip
        pip install looker-sdk
        pip install pyyaml
        pip install jsonschema 
        pip install pytest
        pip install lkml
        
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Snazzy Linter
      run: |
        python -m .github/lookml-linter-main/linter.main config.example.yaml
        echo "Hello World"
